#!/usr/bin/env node
/* =====================================================================
   Orchestrator: pull new Userback feedback, ask Claude to propose a
   change, push a feature branch and open a DRAFT pull request for each.
   The repo's state.json (committed to main at the end) tracks which
   feedback IDs have been processed so we never double-process.
   ===================================================================== */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { execSync } from "node:child_process";

import { fetchNewFeedback } from "./userback.mjs";
import { analyseAndFix } from "./claude.mjs";

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(SCRIPT_DIR, "..", "..");
const STATE_FILE = path.join(SCRIPT_DIR, "state.json");

const REPO = process.env.REPO; // e.g. sfar2001/easycarehubWeb
const LIMIT = Number(process.env.LIMIT || "0");
const DRY_RUN = !!process.env.DRY_RUN;

function sh(cmd, opts = {}) {
  console.log(`$ ${cmd}`);
  return execSync(cmd, { stdio: "inherit", cwd: REPO_ROOT, ...opts });
}

function shq(cmd) {
  return execSync(cmd, { cwd: REPO_ROOT, encoding: "utf8" }).trim();
}

function loadState() {
  if (!fs.existsSync(STATE_FILE)) return { processed: [] };
  try {
    const j = JSON.parse(fs.readFileSync(STATE_FILE, "utf8"));
    if (!Array.isArray(j.processed)) j.processed = [];
    return j;
  } catch (err) {
    console.warn("state.json unreadable, starting fresh:", err.message);
    return { processed: [] };
  }
}

function saveState(state) {
  fs.writeFileSync(STATE_FILE, JSON.stringify(state, null, 2) + "\n");
}

function truncate(s, n) {
  if (!s) return "";
  return s.length <= n ? s : s.slice(0, n - 1) + "…";
}

function buildBranchName(fb) {
  return `feedback/fb-${fb.id}`;
}

function buildPrTitle(fb) {
  const teaser = truncate(fb.title || fb.comment || "untitled feedback", 60);
  return `Feedback #${fb.id}: ${teaser}`;
}

function buildPrBody(fb, result) {
  const fields = [
    ["Reporter", fb.name || fb.email || "anonymous"],
    ["Category", fb.category || "—"],
    ["Priority", fb.priority || "—"],
    ["Page", fb.url || "—"],
    ["Browser / OS", [fb.browser_name, fb.os_name].filter(Boolean).join(" / ") || "—"],
    ["Submitted", fb.created_at],
  ]
    .map(([k, v]) => `- **${k}:** ${v}`)
    .join("\n");

  const files = result.filesChanged.length
    ? result.filesChanged.map((f) => `- \`${f}\``).join("\n")
    : "_No files changed — review the analysis below._";

  return `## 🗣️ User feedback  \`#${fb.id}\`

> ${fb.comment ? fb.comment.split("\n").join("\n> ") : "_(no body)_"}

${fields}

---

## 🤖 Claude's analysis

${result.summary || "_(Claude did not produce a summary.)_"}

### Files changed

${files}

---

_This PR is a draft. Merging it to \`main\` will trigger a Netlify redeploy.
Generated by the Userback → Claude bot._`;
}

async function main() {
  if (!REPO) throw new Error("REPO env var not set (expected like 'owner/name').");

  const state = loadState();
  console.log(`Loaded state: ${state.processed.length} previously processed id(s).`);

  console.log("Fetching feedback from Userback…");
  const feedback = await fetchNewFeedback(state.processed, LIMIT);
  console.log(`${feedback.length} new feedback item(s).`);
  if (feedback.length === 0) return;

  // Make sure we start from a clean main
  sh("git fetch origin main");
  sh("git checkout main");
  sh("git reset --hard origin/main");

  const newlyProcessed = [];

  for (const fb of feedback) {
    console.log(`\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`);
    console.log(`Processing #${fb.id}: ${truncate(fb.title || fb.comment, 80)}`);

    const branch = buildBranchName(fb);

    // Ensure we're fresh from main
    sh("git checkout main");
    sh("git reset --hard origin/main");

    // Drop any pre-existing branch (local or remote) — we always rebuild.
    try { sh(`git branch -D ${branch}`); } catch { /* ignored */ }
    sh(`git checkout -b ${branch}`);

    let result;
    try {
      result = await analyseAndFix(fb, REPO_ROOT);
    } catch (err) {
      console.error("Claude failed:", err);
      result = {
        summary: `Claude errored: ${err.message}. Please investigate this feedback manually.`,
        filesChanged: [],
        shouldOpenPr: false,
      };
    }

    const hasDirtyTree = shq("git status --porcelain").length > 0;

    if (result.shouldOpenPr && (result.filesChanged.length > 0 || hasDirtyTree)) {
      sh("git add -A");
      const commitMsg = `feedback/${fb.id}: ${truncate(fb.title || fb.comment, 50)}`;
      sh(`git commit -m ${JSON.stringify(commitMsg)}`);

      if (DRY_RUN) {
        console.log("DRY_RUN set — skipping push and PR creation.");
      } else {
        sh(`git push -u origin ${branch}`);

        const bodyFile = path.join(SCRIPT_DIR, `.pr-body-${fb.id}.md`);
        fs.writeFileSync(bodyFile, buildPrBody(fb, result));
        sh(
          `gh pr create --draft --repo ${REPO} --base main --head ${branch} ` +
          `--title ${JSON.stringify(buildPrTitle(fb))} ` +
          `--body-file ${JSON.stringify(bodyFile)}`
        );
        fs.unlinkSync(bodyFile);
      }
    } else {
      console.log(`No code change for #${fb.id}. Summary: ${result.summary}`);
      // Clean branch
      sh("git checkout main");
      try { sh(`git branch -D ${branch}`); } catch { /* ignored */ }
    }

    newlyProcessed.push(fb.id);
  }

  // Commit updated state.json on main
  sh("git checkout main");
  sh("git reset --hard origin/main");

  const state2 = loadState();
  for (const id of newlyProcessed) {
    if (!state2.processed.includes(id)) state2.processed.push(id);
  }
  saveState(state2);

  if (shq("git status --porcelain scripts/feedback-to-pr/state.json").length > 0) {
    sh("git add scripts/feedback-to-pr/state.json");
    const msg = `feedback-bot: mark ${newlyProcessed.length} item(s) processed [skip netlify]`;
    sh(`git commit -m ${JSON.stringify(msg)}`);
    if (!DRY_RUN) sh("git push origin main");
  } else {
    console.log("No state changes to commit.");
  }

  console.log(`\n✓ Done. Processed ${newlyProcessed.length} feedback item(s).`);
}

main().catch((err) => {
  console.error("\n✗ Bot failed:", err);
  process.exit(1);
});
