#!/usr/bin/env node
/* =====================================================================
   Orchestrator: pull new Tally submissions, ask Claude to propose a
   change, push a feature branch and open a DRAFT pull request for each.
   The state file (committed to main at the end) tracks which submission
   IDs have been processed so we never double-process.
   ===================================================================== */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { execSync } from "node:child_process";

import { fetchNewSubmissions } from "./tally.mjs";
import { analyseAndFix } from "./claude.mjs";

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(SCRIPT_DIR, "..", "..");
const STATE_FILE = path.join(SCRIPT_DIR, "state.json");

const REPO = process.env.REPO;              // e.g. sfar2001/easycarehubWeb
const FORM_ID = process.env.TALLY_FORM_ID;  // e.g. WOp6Qv
const LIMIT = Number(process.env.LIMIT || "0");
const DRY_RUN = !!process.env.DRY_RUN;

function sh(cmd, opts = {}) {
  console.log(`$ ${cmd}`);
  return execSync(cmd, { stdio: "inherit", cwd: REPO_ROOT, ...opts });
}
function shq(cmd) {
  return execSync(cmd, { cwd: REPO_ROOT, encoding: "utf8" }).trim();
}

function loadState() {
  if (!fs.existsSync(STATE_FILE)) return { processed: [] };
  try {
    const j = JSON.parse(fs.readFileSync(STATE_FILE, "utf8"));
    if (!Array.isArray(j.processed)) j.processed = [];
    return j;
  } catch (err) {
    console.warn("state.json unreadable, starting fresh:", err.message);
    return { processed: [] };
  }
}
function saveState(state) {
  fs.writeFileSync(STATE_FILE, JSON.stringify(state, null, 2) + "\n");
}

function truncate(s, n) { return s && s.length > n ? s.slice(0, n - 1) + "…" : (s || ""); }
function buildBranchName(fb)  { return `feedback/fb-${fb.id}`; }
function buildPrTitle(fb)     { return `Feedback ${fb.id}: ${truncate(fb.message, 60) || "untitled"}`; }

function buildPrBody(fb, result) {
  const fields = [
    ["Reporter",  fb.name || "anonymous"],
    ["Email",     fb.email || "—"],
    ["Page",      fb.page_url || "—"],
    ["Submitted", fb.created_at],
    ["Form",      fb.form_id],
  ].map(([k, v]) => `- **${k}:** ${v}`).join("\n");

  const files = result.filesChanged.length
    ? result.filesChanged.map((f) => `- \`${f}\``).join("\n")
    : "_No files changed — review the analysis below._";

  const quoted = fb.message ? fb.message.split("\n").join("\n> ") : "_(no body)_";

  return `## 🗣️ User feedback

> ${quoted}

${fields}

---

## 🤖 Claude's analysis

${result.summary || "_(Claude did not produce a summary.)_"}

### Files changed

${files}

---

_This PR is a draft. Merging it to \`main\` will trigger a Netlify redeploy.
Generated by the Tally → Claude bot._`;
}

async function main() {
  if (!REPO) throw new Error("REPO env var not set (expected like 'owner/name').");
  if (!FORM_ID) throw new Error("TALLY_FORM_ID env var not set.");

  const state = loadState();
  console.log(`Loaded state: ${state.processed.length} previously processed id(s).`);

  console.log(`Fetching submissions from Tally (form ${FORM_ID})…`);
  const feedback = await fetchNewSubmissions(FORM_ID, state.processed, LIMIT);
  console.log(`${feedback.length} new submission(s).`);
  if (feedback.length === 0) return;

  sh("git fetch origin main");
  sh("git checkout main");
  sh("git reset --hard origin/main");

  const newlyProcessed = [];

  for (const fb of feedback) {
    console.log(`\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`);
    console.log(`Processing ${fb.id}: ${truncate(fb.message, 80)}`);

    const branch = buildBranchName(fb);

    sh("git checkout main");
    sh("git reset --hard origin/main");

    try { sh(`git branch -D ${branch}`); } catch { /* ignore */ }
    sh(`git checkout -b ${branch}`);

    let result;
    try {
      result = await analyseAndFix(fb, REPO_ROOT);
    } catch (err) {
      console.error("Claude failed:", err);
      result = {
        summary: `Claude errored: ${err.message}. Please investigate this feedback manually.`,
        filesChanged: [],
        shouldOpenPr: false,
      };
    }

    const dirty = shq("git status --porcelain").length > 0;

    if (result.shouldOpenPr && (result.filesChanged.length > 0 || dirty)) {
      sh("git add -A");
      sh(`git commit -m ${JSON.stringify(`feedback/${fb.id}: ${truncate(fb.message, 50) || "proposed fix"}`)}`);

      if (DRY_RUN) {
        console.log("DRY_RUN set — skipping push and PR creation.");
      } else {
        sh(`git push -u origin ${branch}`);
        const bodyFile = path.join(SCRIPT_DIR, `.pr-body-${fb.id}.md`);
        fs.writeFileSync(bodyFile, buildPrBody(fb, result));
        sh(
          `gh pr create --draft --repo ${REPO} --base main --head ${branch} ` +
          `--title ${JSON.stringify(buildPrTitle(fb))} ` +
          `--body-file ${JSON.stringify(bodyFile)}`
        );
        fs.unlinkSync(bodyFile);
      }
    } else {
      console.log(`No code change for ${fb.id}. Summary: ${result.summary}`);
      sh("git checkout main");
      try { sh(`git branch -D ${branch}`); } catch { /* ignore */ }
    }

    newlyProcessed.push(fb.id);
  }

  // Commit updated state.json on main
  sh("git checkout main");
  sh("git reset --hard origin/main");

  const state2 = loadState();
  for (const id of newlyProcessed) {
    if (!state2.processed.includes(id)) state2.processed.push(id);
  }
  saveState(state2);

  if (shq("git status --porcelain scripts/feedback-to-pr/state.json").length > 0) {
    sh("git add scripts/feedback-to-pr/state.json");
    sh(`git commit -m ${JSON.stringify(`feedback-bot: mark ${newlyProcessed.length} item(s) processed [skip netlify]`)}`);
    if (!DRY_RUN) sh("git push origin main");
  } else {
    console.log("No state changes to commit.");
  }

  console.log(`\n✓ Done. Processed ${newlyProcessed.length} submission(s).`);
}

main().catch((err) => {
  console.error("\n✗ Bot failed:", err);
  process.exit(1);
});
